version: '3'

services:
  django:
    build: ./backend
    ports:
      - "8000:8000"

  frontend:
    stdin_open: true
    depends_on:
        - django
    build: ./frontend
    ports:
      - "3000:3000"
