# Generated by Django 3.0.4 on 2020-05-13 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('compay_name', models.TextField(blank=True, verbose_name='company name')),
                ('job_description', models.TextField(blank=True, verbose_name='job description')),
                ('country', models.TextField(blank=True, verbose_name='country')),
                ('city', models.TextField(blank=True, verbose_name='city')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('job_selector', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobId', to='Jobs.Jobs')),
            ],
        ),
    ]
