# Generated by Django 3.0.4 on 2020-05-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('compay_name', models.CharField(blank=True, max_length=100, verbose_name='company name')),
                ('job_description', models.CharField(blank=True, max_length=100, verbose_name='job description')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='country')),
                ('city', models.CharField(blank=True, max_length=30, verbose_name='city')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='application_status',
            field=models.CharField(choices=[('open', 'open'), ('rejected', 'rejected'), ('interview', 'interview')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='history',
            name='job_selector',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobId', to='Jobs.Job'),
        ),
        migrations.DeleteModel(
            name='Jobs',
        ),
    ]
